# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Reportree

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'    
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'    

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout main module
      uses: actions/checkout@v3
      with:
        submodules: 'true' 
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        activate-environment: reportree
        environment-file: reportree_env.yml
        auto-activate-base: false
    - name: Test with pytest
      run: |
        pytest
        
